### ISSUE TITLE
Reduce API by using {err, value}

### ISSUE THREAD

**Issue by fregante** [sindresorhus/p-reflect#2]
Instead of resolving with this verbose object:

```js
{
        isFulfilled: true,
        isRejected: false,
        value: '🦄'
}
{
        isFulfilled: false,
        isRejected: true,
        reason: [Error: 👹]
}
```

It could return the equivalent of node callbacks:

```js
{
        //err: undefined,
        value: '🦄'
}
{
        err: [Error: 👹],
        //value: undefined
}
```

Just a thought, naming could be better. It feels weird to have two properties for the same exact purpose (`isFulfilled` and `isRejected` are opposites)

**Comment by sindresorhus** [comment]
I actually [did](https://github.com/sindresorhus/p-settle/commit/b35b2e52b6e0ad44ef8888ad0a2b63f52a56d225#diff-0730bb7c2e8f9ea2438b52e419dd86c9L27) what you're suggesting initially, but later decided to add those properties for convenience. They make it easier to filter the results.

**Comment by fregante** [comment]
I guess that works. `err`/`value` are still similarly available as `reason`/`value` :)

I had just found it curious that you eventually reinvented node-style callbacks :D

**Comment by sindresorhus** [comment]
I forgot to mention the most important reason, it's to prevent people from accidentally doing `value ? value : reason`, as `value` can be `undefined`, but still be fulfilled. I actually did that a couple of times myself.

> I had just found it curious that you eventually reinvented node-style callbacks :D

I think you're mistaken. This has nothing to do with node-style callback, but rather the ability to prevent early exits in loop by handling successes/failures afterwards.

**Comment by fregante** [comment]
Yeah, you're right about that. `Promise.reject()` would have an undefined reason too.

I understand the use of p-reflect and I've needed it in the past, but:

By callbacks I mean _**one function** that is called regardless of errors, in which you handle errors:_

```js
fn((err, value) => {
    if (err) {
        console.error(err);
        return;
    }
    save(value);
});
pReflect(res => {
    if (res.isRejected) {
        console.error(res.reason);
        return;
    }
    save(res.value);
});
```

😜
