### ISSUE TITLE
Consider changing promise.resolve to promise.all

### ISSUE THREAD

**Issue by AslanGoldenhour** [sindresorhus/p-reflect#3]
I'm trying to run a series of API calls through p-retry and p-reflect, and what I'm finding is that I can't resolve nested promises. 

Would you consider changing: `module.exports = promise => Promise.resolve(promise).then(`
to: `module.exports = promise => Promise.all(promise).then(`

**Comment by sindresorhus** [comment]
`Promise.all` accepts an iterable, not a promise. It's not really clear what you're trying to achieve.
